import { NodeCategory, NodeDef } from '../../types';

export const NODE_DEFS: NodeDef[] = [
  { category: 'people', type: 'operator', label: 'Operator', icon: '👤' },
  { category: 'people', type: 'technician', label: 'Technician', icon: '🔧' },
  { category: 'people', type: 'team_lead', label: 'Team Lead', icon: '👑' },
  { category: 'people', type: 'supervisor', label: 'Supervisor', icon: '📋' },
  { category: 'people', type: 'manager', label: 'Manager', icon: '💼' },
  { category: 'people', type: 'engineer', label: 'Engineer', icon: '⚙️' },
  { category: 'people', type: 'inspector', label: 'Inspector', icon: '🔍' },
  { category: 'people', type: 'trainer', label: 'Trainer', icon: '📚' },
  { category: 'people', type: 'hr_specialist', label: 'HR Specialist', icon: '🤝' },
  { category: 'production', type: 'assembly', label: 'Assembly', icon: '🏭' },
  { category: 'production', type: 'fabrication', label: 'Fabrication', icon: '🔩' },
  { category: 'production', type: 'machining', label: 'Machining', icon: '🛠️' },
  { category: 'production', type: 'welding', label: 'Welding', icon: '🔥' },
  { category: 'production', type: 'painting', label: 'Painting', icon: '🎨' },
  { category: 'production', type: 'packaging', label: 'Packaging', icon: '📦' },
  { category: 'production', type: 'molding', label: 'Molding', icon: '♻️' },
  { category: 'production', type: 'stamping', label: 'Stamping', icon: '🔨' },
  { category: 'production', type: 'production_cell', label: 'Prod Cell', icon: '⚡' },
  { category: 'machinery', type: 'cnc_machine', label: 'CNC Machine', icon: '⚙️' },
  { category: 'machinery', type: 'conveyor', label: 'Conveyor', icon: '📎' },
  { category: 'machinery', type: 'robot', label: 'Robot', icon: '🤖' },
  { category: 'machinery', type: 'press', label: 'Press', icon: '⬇️' },
  { category: 'machinery', type: 'oven', label: 'Oven', icon: '🔥' },
  { category: 'machinery', type: 'cooling_tower', label: 'Cooling Tower', icon: '❄️' },
  { category: 'machinery', type: 'compressor', label: 'Compressor', icon: '💨' },
  { category: 'machinery', type: 'generator', label: 'Generator', icon: '🔋' },
  { category: 'machinery', type: 'pump', label: 'Pump', icon: '💧' },
  { category: 'quality', type: 'quality_check', label: 'Quality Check', icon: '✓' },
  { category: 'quality', type: 'testing', label: 'Testing', icon: '🧪' },
  { category: 'quality', type: 'calibration', label: 'Calibration', icon: '📏' },
  { category: 'quality', type: 'certification', label: 'Certification', icon: '📜' },
  { category: 'quality', type: 'audit', label: 'Audit', icon: '📝' },
  { category: 'quality', type: 'inspection_station', label: 'Inspection', icon: '🔎' },
  { category: 'warehouse', type: 'receiving', label: 'Receiving', icon: '📥' },
  { category: 'warehouse', type: 'storage', label: 'Storage', icon: '🗄️' },
  { category: 'warehouse', type: 'picking', label: 'Picking', icon: '🎯' },
  { category: 'warehouse', type: 'packing', label: 'Packing', icon: '📦' },
  { category: 'warehouse', type: 'shipping', label: 'Shipping', icon: '📤' },
  { category: 'warehouse', type: 'inventory', label: 'Inventory', icon: '📊' },
  { category: 'warehouse', type: 'cross_docking', label: 'Cross Dock', icon: '🔄' },
  { category: 'logistics', type: 'inbound', label: 'Inbound', icon: '🚚' },
  { category: 'logistics', type: 'outbound', label: 'Outbound', icon: '🚛' },
  { category: 'logistics', type: 'fleet_mgmt', label: 'Fleet Mgmt', icon: '🚗' },
  { category: 'logistics', type: 'route_plan', label: 'Route Plan', icon: '🗺️' },
  { category: 'logistics', type: 'dispatch', label: 'Dispatch', icon: '📡' },
  { category: 'logistics', type: 'tracking', label: 'Tracking', icon: '📍' },
  { category: 'maintenance', type: 'preventive', label: 'Preventive', icon: '🛡️' },
  { category: 'maintenance', type: 'corrective', label: 'Corrective', icon: '🔧' },
  { category: 'maintenance', type: 'predictive', label: 'Predictive', icon: '🔮' },
  { category: 'maintenance', type: 'repair', label: 'Repair', icon: '🩹' },
  { category: 'maintenance', type: 'overhaul', label: 'Overhaul', icon: '🔄' },
  { category: 'maintenance', type: 'lubrication', label: 'Lubrication', icon: '🛢️' },
  { category: 'kpi', type: 'oee', label: 'OEE', icon: '📈' },
  { category: 'kpi', type: 'throughput', label: 'Throughput', icon: '📊' },
  { category: 'kpi', type: 'uptime', label: 'Uptime', icon: '⏱️' },
  { category: 'kpi', type: 'downtime', label: 'Downtime', icon: '⏸️' },
  { category: 'kpi', type: 'yield', label: 'Yield', icon: '🎯' },
  { category: 'kpi', type: 'scrap_rate', label: 'Scrap Rate', icon: '🗑️' },
  { category: 'kpi', type: 'cycle_time', label: 'Cycle Time', icon: '⏳' },
  { category: 'kpi', type: 'quality_score', label: 'Quality Score', icon: '🏆' },
  { category: 'planning', type: 'production_plan', label: 'Prod Plan', icon: '📋' },
  { category: 'planning', type: 'scheduling', label: 'Scheduling', icon: '📅' },
  { category: 'planning', type: 'capacity', label: 'Capacity', icon: '📏' },
  { category: 'planning', type: 'forecasting', label: 'Forecasting', icon: '🔮' },
  { category: 'planning', type: 'bom', label: 'Bill of Mat.', icon: '📑' },
  { category: 'planning', type: 'work_order', label: 'Work Order', icon: '📝' },
  { category: 'safety', type: 'safety_officer', label: 'Safety Officer', icon: '🦺' },
  { category: 'safety', type: 'training', label: 'Safety Training', icon: '📚' },
  { category: 'safety', type: 'incident_report', label: 'Incident Rpt', icon: '⚠️' },
  { category: 'safety', type: 'ppe', label: 'PPE Station', icon: '🪖' },
  { category: 'safety', type: 'emergency', label: 'Emergency', icon: '🚨' },
  { category: 'customer', type: 'customer_order', label: 'Cust Order', icon: '🛒' },
  { category: 'customer', type: 'customer_support', label: 'Cust Support', icon: '🎧' },
  { category: 'customer', type: 'returns', label: 'Returns', icon: '↩️' },
  { category: 'customer', type: 'feedback', label: 'Feedback', icon: '💬' },
  { category: 'customer', type: 'supplier', label: 'Supplier', icon: '🚚' },
  { category: 'customer', type: 'procurement', label: 'Procurement', icon: '📦' },
  { category: 'finance', type: 'cost_center', label: 'Cost Center', icon: '💰' },
  { category: 'finance', type: 'budget', label: 'Budget', icon: '📊' },
  { category: 'finance', type: 'invoicing', label: 'Invoicing', icon: '🧾' },
  { category: 'finance', type: 'payroll', label: 'Payroll', icon: '💵' },
  { category: 'finance', type: 'accounting', label: 'Accounting', icon: '📒' },
  { category: 'finance', type: 'audit_finance', label: 'Finance Audit', icon: '🔍' },
  { category: 'data', type: 'data_collect', label: 'Data Collect', icon: '📡' },
  { category: 'data', type: 'data_analytics', label: 'Analytics', icon: '📊' },
  { category: 'data', type: 'dashboard', label: 'Dashboard', icon: '🖥️' },
  { category: 'data', type: 'alert', label: 'Alert', icon: '🔔' },
  { category: 'data', type: 'reporting', label: 'Reporting', icon: '📑' },
  { category: 'data', type: 'ml_model', label: 'ML Model', icon: '🧠' },
  { category: 'data', type: 'erp_integration', label: 'ERP Integration', icon: '🔗' },
  { category: 'data', type: 'data_quality', label: 'Data Quality', icon: '✅' },
  { category: 'data', type: 'anomaly_detect', label: 'Anomaly Det.', icon: '📉' },
  { category: 'data', type: 'sensor', label: 'Sensor', icon: '📟' },
];

export const NODE_DEF_MAP = new Map(NODE_DEFS.map((d) => [d.type, d]));

export const CATEGORY_ORDER: NodeCategory[] = [
  'people', 'production', 'machinery', 'quality',
  'warehouse', 'logistics', 'maintenance', 'kpi',
  'planning', 'safety', 'customer', 'finance', 'data',
];

export const CATEGORY_LABELS: Record<string, string> = {
  people: 'People', production: 'Production', machinery: 'Machinery',
  quality: 'Quality', warehouse: 'Warehouse', logistics: 'Logistics',
  maintenance: 'Maintenance', kpi: 'KPI', planning: 'Planning',
  safety: 'Safety', customer: 'Customer / Supplier', finance: 'Finance',
  data: 'Data / Alerts',
};

export const NODE_TYPE_CATEGORY: Record<string, NodeCategory> = {};
NODE_DEFS.forEach((d) => { NODE_TYPE_CATEGORY[d.type] = d.category; });

export const ICON_MAP: Record<string, string> = {};
NODE_DEFS.forEach((d) => { ICON_MAP[d.type] = d.icon; });
